apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-app-multi-components-repo-b64x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-app-multi-components-repo-b64x
    app.kubernetes.io/part-of: my-app
  name: python-app-multi-components-repo-b64x
  namespace: karthik-jk-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-app-multi-components-repo-b64x
    weight: 100
status: {}
