apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup-spring-boot-6iuk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup-spring-boot-6iuk
    app.kubernetes.io/part-of: my-app
  name: stonesoup-spring-boot-6iuk
  namespace: karthik-jk-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: stonesoup-spring-boot-6iuk
status:
  loadBalancer: {}
