apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-app-multi-components-repo-bnt1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-app-multi-components-repo-bnt1
    app.kubernetes.io/part-of: my-app
  name: nodejs-app-multi-components-repo-bnt1
  namespace: karthik-jk-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-app-multi-components-repo-bnt1
    weight: 100
status: {}
